apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: saytruth-dev
  labels:
    app: frontend
spec:
  selector:
    app: frontend
  ports:
    - port: 5173
      targetPort: 5173
      protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: saytruth-prod
  labels:
    app: frontend
spec:
  selector:
    app: frontend
  ports:
    - port: 5173
      targetPort: 5173
      protocol: TCP
  type: ClusterIP
